# GitHub Actions workflow for building Windows 11 Pro images using Packer
# This workflow automates the entire image building process from validation to deployment
name: Build Windows Image

# Trigger this workflow when code is pushed to the main branch
# This ensures that any changes to the image configuration are automatically built and tested
on:
  push:
    branches:
      - main

# Define the jobs that will run as part of this workflow
jobs:
  # Main job for building the Packer image
  build-packer-image:
    # Use the latest Ubuntu runner for consistent and reliable builds
    runs-on: ubuntu-latest
    
    # Define the sequence of steps to execute
    steps:
      # Step 1: Checkout the repository code
      # This downloads the entire repository content including Packer templates and provisioning scripts
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      # Step 2: Setup Packer CLI tool
      # This installs the latest version of Packer and makes it available in the workflow
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
      
      # Step 3: Validate the Packer template
      # This checks the syntax and configuration of the Packer template before attempting to build
      - name: Validate Packer Template
        run: packer validate packer/windows_11_pro.pkr.hcl
        # Uncomment and configure these environment variables for Azure authentication
        # These should be stored as GitHub repository secrets for security
        # env:
        #   AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        #   AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        #   AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        #   AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      
      # Step 4: Build the image using Packer
      # This executes the actual image building process with all provisioning steps
      - name: Build Packer Image
        run: packer build packer/windows_11_pro.pkr.hcl
        # Uncomment and configure these environment variables for Azure authentication
        # These credentials allow Packer to create resources in your Azure subscription
        # env:
        #   AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        #   AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        #   AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        #   AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}