name: Build Kairos Images with Factory Action

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'packer/kairos/**'
      - 'scripts/kairos/**'
      - '.github/workflows/kairos-factory.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'packer/kairos/**'
      - 'scripts/kairos/**'
      - '.github/workflows/kairos-factory.yml'
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version to build'
        required: false
        default: '1.0.0'
        type: string
      base_image:
        description: 'Base image (ubuntu:22.04, ubuntu:24.04, etc.)'
        required: false
        default: 'ubuntu:22.04'
        type: string
      arch:
        description: 'Target architecture'
        required: false
        default: 'amd64'
        type: choice
        options:
          - 'amd64'
          - 'arm64'

env:
  VERSION: ${{ inputs.version || '1.0.0' }}
  BASE_IMAGE: ${{ inputs.base_image || 'ubuntu:22.04' }}
  ARCH: ${{ inputs.arch || 'amd64' }}

jobs:
  generate-version:
    name: Generate Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      is_release: ${{ steps.version.outputs.is_release }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper tag detection
          
      - name: Generate version from git tag
        id: version
        run: |
          # For manual workflow dispatch, use input version if provided
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.version }}" ]; then
            VERSION="${{ github.event.inputs.version }}"
            IS_RELEASE="true"
            echo "Using manual version: $VERSION"
          elif git describe --tags --exact-match HEAD 2>/dev/null; then
            # This is a tagged commit - use the tag as version
            VERSION=$(git describe --tags --exact-match HEAD | sed 's/^v//')
            IS_RELEASE="true"
            echo "Using git tag version: $VERSION"
          else
            # This is not a tagged commit - generate development version
            COMMIT_COUNT=$(git rev-list --count HEAD)
            # Check if we have any tags at all
            if git tag -l | grep -q .; then
              LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null)
              BASE_VERSION="${LATEST_TAG#v}"
              # Parse version components
              if [[ "$BASE_VERSION" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
                MAJOR="${BASH_REMATCH[1]}"
                MINOR="${BASH_REMATCH[2]}"
                PATCH="${BASH_REMATCH[3]}"
                NEW_PATCH=$((PATCH + 1))
                VERSION="${MAJOR}.${MINOR}.${NEW_PATCH}"
              else
                # Fallback if tag parsing fails
                VERSION="1.0.1"
              fi
            else
              # No tags exist - start from 1.0.0
              VERSION="1.0.1"
            fi
            IS_RELEASE="false"
            echo "Generated development version: $VERSION"
          fi
          
          # Validate version format
          if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "ERROR: Generated version '$VERSION' is not valid semver format"
            exit 1
          fi
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "is_release=$IS_RELEASE" >> $GITHUB_OUTPUT
          echo "Final version: $VERSION (release: $IS_RELEASE)"
          echo "DEBUG: Raw version output: '$VERSION'"
          echo "DEBUG: Version length: ${#VERSION}"
          echo "DEBUG: Semver validation: PASSED"

  build-iso:
    name: Build Kairos ISO
    needs: generate-version
    uses: kairos-io/kairos-factory-action/.github/workflows/reusable-factory.yaml@v0.0.4
    permissions:
      contents: write
      security-events: write
      id-token: write
      actions: read
      packages: write
    with:
      version: ${{ needs.generate-version.outputs.version }}
      base_image: ${{ github.event.inputs.base_image || 'ubuntu:22.04' }}
      model: "generic"
      iso: true
      arch: ${{ github.event.inputs.arch || 'amd64' }}
      kubernetes_distro: "k3s"
      security_checks: "grype,trivy"
      
  build-raw:
    name: Build Kairos RAW
    needs: generate-version
    uses: kairos-io/kairos-factory-action/.github/workflows/reusable-factory.yaml@v0.0.4
    permissions:
      contents: write
      security-events: write
      id-token: write
      actions: read
      packages: write
    with:
      version: ${{ needs.generate-version.outputs.version }}
      base_image: ${{ github.event.inputs.base_image || 'ubuntu:22.04' }}
      model: "generic"
      raw: true
      arch: ${{ github.event.inputs.arch || 'amd64' }}
      kubernetes_distro: "k3s"
      security_checks: "grype,trivy"


  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [generate-version, build-iso, build-raw]
    if: needs.generate-version.outputs.is_release == 'true' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download ISO artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: "*.iso*"
          path: ./artifacts/iso
          merge-multiple: true

      - name: Download RAW artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: "*.raw*"
          path: ./artifacts/raw
          merge-multiple: true


      - name: List downloaded artifacts
        run: |
          echo "Downloaded artifacts:"
          find ./artifacts -type f -name "*.iso*" -o -name "*.raw*" | sort
          
      - name: Check and compress large files
        run: |
          echo "Checking file sizes and compressing if necessary..."
          MAX_SIZE=$((2 * 1024 * 1024 * 1024))  # 2GB in bytes
          
          for file in $(find ./artifacts -type f -name "*.iso" -o -name "*.raw"); do
            SIZE=$(stat -c%s "$file" 2>/dev/null || stat -f%z "$file")
            echo "File: $file, Size: $SIZE bytes ($(($SIZE / 1024 / 1024))MB)"
            
            if [ $SIZE -gt $MAX_SIZE ]; then
              echo "File $file exceeds 2GB limit, compressing with xz..."
              xz -9 -T0 "$file"
              echo "Compressed: ${file}.xz"
            fi
          done
          
          # Update checksums for compressed files
          for compressed in $(find ./artifacts -name "*.xz"); do
            echo "Generating checksum for $compressed"
            sha256sum "$compressed" > "${compressed}.sha256"
          done
          
          echo "Final artifact list with sizes:"
          find ./artifacts -type f \( -name "*.iso*" -o -name "*.raw*" -o -name "*.xz*" \) -exec ls -lh {} \;
          
      - name: Generate release tag
        id: tag
        run: |
          VERSION="${{ needs.generate-version.outputs.version }}"
          if [[ "${{ needs.generate-version.outputs.is_release }}" == "false" ]]; then
            # Development version - use timestamp for uniqueness
            TAG="kairos-dev-${VERSION}-$(date +'%Y%m%d-%H%M%S')"
          else
            # Release version - use clean semantic version
            TAG="v${VERSION}"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Generated release tag: $TAG"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: Kairos Factory Images ${{ steps.tag.outputs.tag }}
          body: |
            ## Kairos Factory Images Release
            
            Built using Kairos Factory Action with enterprise configuration.
            
            ### Images Included:
            - **ISO Images**: Ready-to-boot Kairos ISO images for bare metal or VM installation
            - **RAW Images**: Raw disk images for direct deployment to virtualization platforms
            
            ### Usage:
            - **ISO**: Boot from ISO to install Kairos on bare metal or create VM templates
            - **RAW**: Direct disk deployment with `dd` command or virtualization tools
            
            ### Configuration:
            - Version: ${{ needs.generate-version.outputs.version }}
            - Base Image: ${{ github.event.inputs.base_image || 'ubuntu:22.04' }}
            - Architecture: ${{ github.event.inputs.arch || 'amd64' }}
            - Kubernetes: K3s with enterprise configuration
            - Security: Vulnerability scanning enabled (Grype + Trivy)
            - Release Type: ${{ needs.generate-version.outputs.is_release == 'true' && 'Official Release' || 'Development Build' }}
            
            Built from commit: ${{ github.sha }}
          files: |
            ./artifacts/iso/*.iso
            ./artifacts/iso/*.iso.sha256
            ./artifacts/iso/*.iso.xz
            ./artifacts/iso/*.iso.xz.sha256
            ./artifacts/raw/*.raw
            ./artifacts/raw/*.raw.sha256
            ./artifacts/raw/*.raw.xz
            ./artifacts/raw/*.raw.xz.sha256
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}