name: Build Kairos Images with Factory Action

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'packer/kairos/**'
      - 'scripts/kairos/**'
      - '.github/workflows/kairos-factory.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'packer/kairos/**'
      - 'scripts/kairos/**'
      - '.github/workflows/kairos-factory.yml'
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version to build'
        required: false
        default: '1.0.0'
        type: string
      base_image:
        description: 'Base image (ubuntu:22.04, ubuntu:24.04, etc.)'
        required: false
        default: 'ubuntu:22.04'
        type: string
      platforms:
        description: 'Target platforms (amd64, arm64, or both)'
        required: false
        default: 'amd64'
        type: choice
        options:
          - 'amd64'
          - 'arm64'
          - 'amd64,arm64'

env:
  VERSION: ${{ inputs.version || '1.0.0' }}
  BASE_IMAGE: ${{ inputs.base_image || 'ubuntu:22.04' }}
  PLATFORMS: ${{ inputs.platforms || 'amd64' }}

jobs:
  build-iso:
    name: Build Kairos ISO
    uses: kairos-io/kairos-factory-action/.github/workflows/reusable-factory.yaml@v0.0.4
    with:
      version: ${{ github.event.inputs.version || '1.0.0' }}
      base_image: ${{ github.event.inputs.base_image || 'ubuntu:22.04' }}
      model: "generic"
      iso: true
      platforms: ${{ github.event.inputs.platforms || 'amd64' }}
      kubernetes_distro: "k3s"
      cloud_config: "packer/kairos/cloud-config.yaml"
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      
  build-raw:
    name: Build Kairos RAW
    uses: kairos-io/kairos-factory-action/.github/workflows/reusable-factory.yaml@v0.0.4
    with:
      version: ${{ github.event.inputs.version || '1.0.0' }}
      base_image: ${{ github.event.inputs.base_image || 'ubuntu:22.04' }}
      model: "generic"
      raw: true
      platforms: ${{ github.event.inputs.platforms || 'amd64' }}
      kubernetes_distro: "k3s"
      cloud_config: "packer/kairos/cloud-config.yaml"
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-iso, build-raw]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate release tag
        id: tag
        run: |
          TAG="kairos-factory-${{ github.event.inputs.version || '1.0.0' }}-$(date +'%Y%m%d-%H%M%S')"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: Kairos Factory Images ${{ steps.tag.outputs.tag }}
          body: |
            ## Kairos Factory Images Release
            
            Built using Kairos Factory Action with enterprise configuration.
            
            ### Images Included:
            - **ISO Images**: Ready-to-boot Kairos ISO images
            - **RAW Images**: Raw disk images for virtualization
            
            ### Configuration:
            - Version: ${{ github.event.inputs.version || '1.0.0' }}
            - Base Image: ${{ github.event.inputs.base_image || 'ubuntu:22.04' }}
            - Platforms: ${{ github.event.inputs.platforms || 'amd64' }}
            - Kubernetes: K3s with enterprise configuration
            - Security: Vulnerability scanning enabled
            
            Built from commit: ${{ github.sha }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}